config/routes.rb
Rijschoolmanager::Application.routes.draw do
  resources :course_types

  resources :lesson_types

  resources :lessons

  resources :pupils do
    resources :courses
  end

  resources :courses do
      resources :lessons
  end

  resources :teachers do
	resources :lessons
  end

  resources :course_types do
    resources :courses
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    if params[:pupil_id]
      @pupil = Pupil.find(params[:pupil_id])
      @courses = @pupil.courses
    else
      @courses = Course.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    @required_hours = @course.course_type.min_minutes / 60
    @completed_hours = 3
    @required_payment = @required_hours * @course.course_type.hourly_rate
    if not @course.already_paid
      @course.already_paid = 0
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new
    @course.pupil = Pupil.find(params[:pupil_id]) if params[:pupil_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new

    @course.pupil = Pupil.find params[:course][:pupil]
    @course.course_type = CourseType.find params[:course][:course_type]

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, :notice => 'Course was successfully created.' }
        format.json { render :json => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.json { render :json => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, :notice => 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_type %><br />
    <%= f.collection_select :course_type, CourseType.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :pupil %><br />
    <%= f.collection_select :pupil, Pupil.all, :id, :full_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Pupil Name</th>
    <th>Course type</th>
    <th>Min hours</th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.pupil.full_name %></td>
    <td><%= course.course_type.name %></td>
    <td><%= course.course_type.min_minutes / 60 %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>
<% if @pupil %>
<%= link_to 'Back', pupil_path(@pupil)%>
<%end%>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pupil Name:</b>
  <%= @course.pupil.full_name %>
</p>

<p>
  <b>Course type:</b>
  <%= @course.course_type.name %>
</p>

<p>
  <b>Min hours:</b>
  <%= "#{@course.course_type.min_minutes / 60} (#{@course.course_type.min_minutes} minutes)" %>
</p>
<p>
  <b>Payment details:</b>
  <%= "amount €#{@course.already_paid} of total €#{@required_payment} , still to pay: €#{@required_payment - @course.already_paid}" %>
</p>

<p>
  <b>Lessons:</b>
</p>
<table class="table table-bordered">
<tr>
<th>#</th>
<th>Begin</th>
<th>End</th>
<th></th>
<th></th>
</tr>
<% @course.lessons.each_with_index do |lesson, index| %>
<tr>
<td><%= index %></td>
<td><%= lesson.start %></td>
<td><%= lesson.end %></td>
<td><%= lesson.lesson_type %></td>
<td><%= link_to 'Show', lesson %></td>
<td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
<td><%= link_to 'Destroy', lesson, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
</table>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>