config/routes.rb
Rijschoolmanager::Application.routes.draw do
  resources :course_types

  resources :lesson_types

  resources :lessons

  resources :pupils do
    resources :courses
  end

  resources :courses do
      resources :lessons
  end

  resources :teachers do
	resources :lessons
  end

  resources :course_types do
    resources :courses
  end

end

app/models/pupil.rb
class Pupil < ActiveRecord::Base
  attr_accessible :first_name, :name, :full_name, :lessons, :courses
  has_many :courses
  has_many :lessons, :through => :courses
  has_many :teachers, :through => :lessons
  
  def full_name
    [first_name, name].join(' ')
  end
end

app/controllers/pupils_controller.rb
class PupilsController < ApplicationController
  # GET /pupils
  # GET /pupils.json
  def index
    @pupils = Pupil.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pupils }
    end
  end

  # GET /pupils/1
  # GET /pupils/1.json
  def show
    @pupil = Pupil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @pupil }
    end
  end

  # GET /pupils/new
  # GET /pupils/new.json
  def new
    @pupil = Pupil.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @pupil }
    end
  end

  # GET /pupils/1/edit
  def edit
    @pupil = Pupil.find(params[:id])
  end

  # POST /pupils
  # POST /pupils.json
  def create
    @pupil = Pupil.new(params[:pupil])

    respond_to do |format|
      if @pupil.save
        format.html { redirect_to @pupil, :notice => 'Pupil was successfully created.' }
        format.json { render :json => @pupil, :status => :created, :location => @pupil }
      else
        format.html { render :action => "new" }
        format.json { render :json => @pupil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pupils/1
  # PUT /pupils/1.json
  def update
    @pupil = Pupil.find(params[:id])

    respond_to do |format|
      if @pupil.update_attributes(params[:pupil])
        format.html { redirect_to @pupil, :notice => 'Pupil was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @pupil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pupils/1
  # DELETE /pupils/1.json
  def destroy
    @pupil = Pupil.find(params[:id])
    @pupil.destroy

    respond_to do |format|
      format.html { redirect_to pupils_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pupils_helper.rb
module PupilsHelper
end

app/views/pupils/_form.html.erb
<%= form_for(@pupil) do |f| %>
  <% if @pupil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pupil.errors.count, "error") %> prohibited this pupil from being saved:</h2>

      <ul>
      <% @pupil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pupils/edit.html.erb
<h1>Editing pupil</h1>

<%= render 'form' %>

<%= link_to 'Show', @pupil %> |
<%= link_to 'Back', pupils_path %>

app/views/pupils/index.html.erb
<h2>Listing pupils</h2>

<table class="table table-striped table-bordered">
  <tr>
    <th>Name</th>
    <th>First name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pupils.each do |pupil| %>
  <tr>
    <td><%= pupil.name %></td>
    <td><%= pupil.first_name %></td>
    <td><%= link_to 'Show', pupil %></td>
    <td><%= link_to 'Edit', edit_pupil_path(pupil) %></td>
    <td><%= link_to 'Destroy', pupil, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pupil', new_pupil_path, {:class => "btn"} %>

app/views/pupils/new.html.erb
<h1>New pupil</h1>

<%= render 'form' %>

<%= link_to 'Back', pupils_path %>

app/views/pupils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pupil.name %>
</p>

<p>
  <b>First name:</b>
  <%= @pupil.first_name %>
</p>
<p>
  <b>Courses:</b>
  <ol>
  <% @pupil.courses.each do |course| %>
      <li> <%= link_to course.course_type.name, course_path(course) %> | <%= link_to 'Add Lesson', new_course_lesson_path(course) %></li>
  <% end %>
  </ol>
</p>


<%= link_to 'New Course', new_pupil_course_path(@pupil) %> |
<%= link_to 'Edit', edit_pupil_path(@pupil) %> |
<%= link_to 'Back', pupils_path %>